/**
 * Load hand-maintained static overrides.
 *
 * Bus shapes preferred source (live):
 *   VITE_OVERRIDES_BUS_SHAPES_URL → GitHub raw (morgan-travelers-overrides repo)
 * Fallback:
 *   public/overrides/bus-shapes.json → offline bundle
 *
 * LRT / MTR access pins still load from public/overrides/.
 * Never generated by collect-open-data / build:fares.
 */

/** Published shapes repo on GitHub. */
export const OVERRIDES_REPO_DEFAULT = "UNGemini/morgan-travelers-overrides";

/**
 * Where to fetch bus-shapes.json:
 * 1. VITE_OVERRIDES_BUS_SHAPES_URL if set
 * 2. In Vite dev: same-origin /api/overrides/bus-shapes.json (local sibling repo)
 * 3. Else GitHub raw (production default)
 */
export function busShapesRemoteUrl() {
  if (
    typeof import.meta !== "undefined" &&
    import.meta.env?.VITE_OVERRIDES_BUS_SHAPES_URL
  ) {
    return String(import.meta.env.VITE_OVERRIDES_BUS_SHAPES_URL);
  }
  if (typeof import.meta !== "undefined" && import.meta.env?.DEV) {
    if (typeof window !== "undefined" && window.location?.origin) {
      return `${window.location.origin}/api/overrides/bus-shapes.json`;
    }
    return "/api/overrides/bus-shapes.json";
  }
  return `https://raw.githubusercontent.com/${OVERRIDES_REPO_DEFAULT}/main/bus-shapes.json`;
}

/** @deprecated use busShapesRemoteUrl() */
export const DEFAULT_BUS_SHAPES_REMOTE =
  typeof import.meta !== "undefined" &&
  import.meta.env?.VITE_OVERRIDES_BUS_SHAPES_URL
    ? String(import.meta.env.VITE_OVERRIDES_BUS_SHAPES_URL)
    : `https://raw.githubusercontent.com/${OVERRIDES_REPO_DEFAULT}/main/bus-shapes.json`;

/** @type {any} */
const LRT_FALLBACK = {
  updated_at: "2026-04-24",
  stops: {
    "Tin Wing": {
      name_zh: "天榮",
      lat: 22.46,
      lon: 114.00222,
      code: "TWI",
      stop_id: "500",
    },
  },
  platforms: {
    "Tin Wing": {
      name_match: ["tin wing", "天榮"],
      centroid: { lon: 114.00222, lat: 22.46 },
      by_ref: {
        "1": { lon: 114.00248, lat: 22.45978 },
        "3": { lon: 114.00228, lat: 22.45995 },
        "4": { lon: 114.00212, lat: 22.46008 },
      },
    },
  },
  shapes: [
    {
      id: "ginza_to_tin_wing",
      from_match: ["ginza", "銀座"],
      to_match: ["tin wing", "天榮"],
      coordinates: [
        [114.004959, 22.457552],
        [114.00455, 22.45795],
        [114.0041, 22.45835],
        [114.00355, 22.45885],
        [114.00305, 22.45925],
        [114.00272, 22.45952],
        [114.00248, 22.45978],
      ],
    },
  ],
  approach_rules: [
    {
      id: "tin_wing_neighbour_approach",
      end_match: ["tin wing", "天榮"],
      use_shape: "ginza_to_tin_wing",
      slice_end: 4,
    },
  ],
};

/** @type {any} */
const MTR_ACCESS_FALLBACK = {
  updated_at: "2026-07-27",
  locked: [
    {
      name_en: "Sha Tin",
      name_zh: "沙田",
      lat: 22.3827,
      lon: 114.1875,
      code: "SHT",
    },
    {
      name_en: "Hong Kong",
      name_zh: "香港",
      code: "HOK",
      lock_coords_only: true,
    },
  ],
};

/** @type {any} */
const BUS_SHAPES_FALLBACK = {
  updated_at: "2026-07-31",
  note: "Reviewed bus path overrides (empty until mods publish contributions).",
  routes: [],
};

let lrtOverrides = LRT_FALLBACK;
let mtrAccessOverrides = MTR_ACCESS_FALLBACK;
let busShapeOverrides = BUS_SHAPES_FALLBACK;
let loadPromise = null;

function baseUrl() {
  const b =
    (typeof import.meta !== "undefined" && import.meta.env?.BASE_URL) || "/";
  return b.endsWith("/") ? b : `${b}/`;
}

/**
 * Fetch overrides: LRT/access from app bundle; bus shapes from remote repo first.
 */
export async function loadStaticOverrides() {
  if (loadPromise) return loadPromise;
  loadPromise = (async () => {
    if (typeof window === "undefined" || !window.location) {
      return {
        lrt: lrtOverrides,
        mtrAccess: mtrAccessOverrides,
        busShapes: busShapeOverrides,
      };
    }
    const root = baseUrl();
    try {
      const localBusUrl = new URL(
        `${root}overrides/bus-shapes.json`,
        window.location.href,
      ).href;
      const remoteBusUrl = busShapesRemoteUrl();

      const [lrtRes, pinRes, busRemoteRes, busLocalRes] = await Promise.all([
        fetch(new URL(`${root}overrides/lrt.json`, window.location.href).href, {
          cache: "no-cache",
        }),
        fetch(
          new URL(`${root}overrides/mtr-access-pins.json`, window.location.href)
            .href,
          { cache: "no-cache" },
        ),
        remoteBusUrl
          ? fetch(remoteBusUrl, {
              cache: "no-cache",
              mode: "cors",
              headers: { Accept: "application/json" },
            }).catch((e) => {
              console.warn("[overrides] bus-shapes remote failed", e);
              return null;
            })
          : Promise.resolve(null),
        fetch(localBusUrl, { cache: "no-cache" }),
      ]);
      if (lrtRes.ok) lrtOverrides = await lrtRes.json();
      if (pinRes.ok) mtrAccessOverrides = await pinRes.json();

      // Prefer remote / local-dev API published shapes; fall back to bundled
      let busSource = "fallback";
      if (busRemoteRes?.ok) {
        try {
          const remote = await busRemoteRes.json();
          if (Array.isArray(remote?.routes)) {
            busShapeOverrides = remote;
            busSource = remoteBusUrl.includes("/api/overrides/")
              ? "local-dev-api"
              : "remote";
          }
        } catch (e) {
          console.warn("[overrides] remote JSON parse failed", e);
        }
      }
      if (busSource === "fallback" && busLocalRes.ok) {
        busShapeOverrides = await busLocalRes.json();
        busSource = "local-bundle";
      }

      console.info(
        "[overrides]",
        "lrt shapes",
        lrtOverrides?.shapes?.length ?? 0,
        "access pins",
        mtrAccessOverrides?.locked?.length ?? 0,
        "bus shapes",
        busShapeOverrides?.routes?.length ?? 0,
        `(${busSource})`,
        remoteBusUrl ? remoteBusUrl.slice(0, 72) : "no remote URL",
      );
    } catch (err) {
      console.warn("[overrides] fetch failed — using fallback", err);
      lrtOverrides = LRT_FALLBACK;
      mtrAccessOverrides = MTR_ACCESS_FALLBACK;
      busShapeOverrides = BUS_SHAPES_FALLBACK;
    }
    return {
      lrt: lrtOverrides,
      mtrAccess: mtrAccessOverrides,
      busShapes: busShapeOverrides,
    };
  })();
  return loadPromise;
}

/**
 * Force re-fetch of bus shapes (e.g. after a long session).
 * Clears the load promise so next get/load hits the network again.
 */
export function invalidateBusShapeOverridesCache() {
  loadPromise = null;
}

export function getLrtOverrides() {
  return lrtOverrides;
}

export function getMtrAccessOverrides() {
  return mtrAccessOverrides;
}

export function getBusShapeOverrides() {
  return busShapeOverrides;
}

/** @returns {Set<string>} */
export function getAccessPinLockSet() {
  const set = new Set();
  for (const p of mtrAccessOverrides?.locked || []) {
    if (p?.name_en) set.add(String(p.name_en).toLowerCase());
  }
  return set;
}

/**
 * @returns {Map<string, { lat: number, lon: number, name_zh?: string, code?: string }>}
 */
export function getAccessPinCoords() {
  const map = new Map();
  for (const p of mtrAccessOverrides?.locked || []) {
    if (!p?.name_en) continue;
    if (Number.isFinite(p.lat) && Number.isFinite(p.lon)) {
      map.set(String(p.name_en).toLowerCase(), {
        lat: p.lat,
        lon: p.lon,
        name_zh: p.name_zh,
        code: p.code,
      });
    }
  }
  return map;
}
